#ifndef CC_PANOPTES_ENGLISH_vERBS_INTERNAL_PARSING_FLAT_VWC_FIELDS_H_
#define CC_PANOPTES_ENGLISH_vERBS_INTERNAL_PARSING_FLAT_VWC_FIELDS_H_

enum FlatVWCField {
    FLAT_LEMMA,
    FLAT_TF,
    FLAT_IS_CONTRARY,
    FLAT_TENSE,
    FLAT_IS_PERF,
    FLAT_IS_PROG,
    FLAT_FLAVOR,
    FLAT_IS_COND,
    FLAT_VERB_FORM,
    FLAT_IS_PRO_VERB,
    FLAT_VOICE,
    FLAT_CONJ,
    FLAT_IS_SPLIT,
    FLAT_REL_CONT,
    FLAT_CONTRACT_NOT,
    FLAT_SPLIT_INF,
    FLAT_SBJ_HANDLING,
    FLAT_NUM_FLATS
};

#endif  // CC_PANOPTES_ENGLISH_vERBS_INTERNAL_PARSING_FLAT_VWC_FIELDS_H_
